// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6f54520d-6849-4080-a08b-6324c823820d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Mi2nCbwEB",
    "aws_user_pools_web_client_id": "6f9ll5jh26ev31cv4clefs7dm3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qebkgoesxbbevgdlir2rlh74au.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
